name: Build with different version
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        version: [10, 11, 12, 13]
    steps:
      - uses: actions/checkout@v2

      - name: Set Ubuntu codename (Bionic)
        if: ${{ matrix.os == 'ubuntu-18.04'}}
        run: echo "UBUNTU_CODENAME=bionic" >> $GITHUB_ENV
      - name: Set Ubuntu codename (Focal)
        if: ${{ matrix.os == 'ubuntu-20.04'}}
        run: echo "UBUNTU_CODENAME=focal" >> $GITHUB_ENV
      - name: Install Dependencies
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          if test ${{ matrix.version }} == 13; then
            sudo apt-add-repository "deb http://apt.llvm.org/${{ env.UBUNTU_CODENAME }}/ llvm-toolchain-${{ env.UBUNTU_CODENAME }} main"
          else
            sudo apt-add-repository "deb http://apt.llvm.org/${{ env.UBUNTU_CODENAME }}/ llvm-toolchain-${{ env.UBUNTU_CODENAME }}-${{ matrix.version }} main"
          fi
          sudo apt-get update
          sudo apt-get install -y clang-${{ matrix.version }} clang-tidy-${{ matrix.version }} clang-format-${{ matrix.version }} clang-tools-${{ matrix.version }} llvm-${{ matrix.version }}-dev lld-${{ matrix.version }} lldb-${{ matrix.version }} llvm-${{ matrix.version }}-tools libomp-${{ matrix.version }}-dev libc++-${{ matrix.version }}-dev libc++abi-${{ matrix.version }}-dev libclang-common-${{ matrix.version }}-dev libclang-${{ matrix.version }}-dev libclang-cpp${{ matrix.version }}-dev
      - name: Run the testsuite
        shell: bash
        run: |
         mkdir build && cd build
         cmake -DLIT=/usr/lib/llvm-${{ matrix.version }}/build/utils/lit/lit.py \
           -DCLANG_BINARY=/usr/bin/clang-${{ matrix.version }} \
           -DCLANGXX_BINARY=/usr/bin/clang++-${{ matrix.version }} \
           -DCLANG_TIDY_BINARY=/usr/bin/clang-tidy-${{ matrix.version }} \
           -DCLANG_FORMAT_BINARY=/usr/bin/clang-format-${{ matrix.version }} \
           -DCLANG_FORMAT_DIFF_BINARY=/usr/bin/clang-format-diff-${{ matrix.version }} \
           -DLLD_BINARY=/usr/bin/lld-${{ matrix.version }} \
           -DLLDB_BINARY=/usr/bin/lldb-${{ matrix.version }} \
           -DLLVMCONFIG_BINARY=/usr/bin/llvm-config-${{ matrix.version }} \
           -DOPT_BINARY=/usr/bin/opt-${{ matrix.version }} \
           -DSCANBUILD=/usr/bin/scan-build-${{ matrix.version }} \
           -DCLANG_TIDY_BINARY=/usr/bin/clang-tidy-${{ matrix.version }} \
           -DSCANVIEW=/usr/bin/scan-view-${{ matrix.version }} \
           -DLLVMNM=/usr/bin/llvm-nm-${{ matrix.version }} \
           -DLLVMPROFDATA=/usr/bin/llvm-profdata-${{ matrix.version }} \
           -DENABLE_COMPILER_RT=ON \
           -DENABLE_LIBCXX=ON \
           ../
         make check
