name: Build on fedora
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: "fedora:34"
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
            sudo dnf install -y llvm-devel clang-devel cmake make python3-lit \
                 lld clang-tools-extra gcc gcc-c++ libcxx-devel compiler-rt libstdc++-devel \
                 glibc-static libstdc++-static mlir mlir-devel
      - name: Run the testsuite
        run: |
         mkdir build && cd build
         cmake .. -DENABLE_COMPILER_RT=ON -DENABLE_LIBCXX=ON
         cmake --build . --target check -v
